project:
  type: website
  output-dir: docs

website:
  title: "Christian Robinson"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/cmrobinson1992
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/christian-robinson-4457949a/
        aria-label: LinkedIn
  page-footer:
    left: "Â© 2025 Christian Robinson"
    right:
      - text: "Email"
        href: "mailto:christian.m.robinson@gmail.com"
      - text: "Resume (PDF)"
        href: "resume.pdf"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    smooth-scroll: true

execute:
  freeze: auto
